:group status check

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -48,35 +48,35 @@ steps:
   - label: "Step 2: Run Setup Script"
     command: "echo 'Running setup script...'"
 
-  - label: "Step 3: This needs to fail and pass on retry :danger:"
-    command: |
-      if [ "$BUILDKITE_RETRY_COUNT" == "1000" ]; then
-        echo "Intentional failure"; exit 1
-      else
-        echo "Retrying and passing with GHPAT_TOKEN..."
-      fi
+  # - label: "Step 3: This needs to fail and pass on retry :danger:"
+  #   command: |
+  #     if [ "$BUILDKITE_RETRY_COUNT" == "1000" ]; then
+  #       echo "Intentional failure"; exit 1
+  #     else
+  #       echo "Retrying and passing with GHPAT_TOKEN..."
+  #     fi
 
-- label: 'Step 5: Update GitHub Status'
-  command: |
-    outcome=$(buildkite-agent step get "state" --step "shopify")
-    if [ "$outcome" != "hard_failed" ]; then
-      echo "Updating GitHub status for parent pipeline with commit hash: $PARENT_COMMIT_HASH"
-      curl -L \
-        -X POST \
-        -H "Accept: application/vnd.github+json" \
-        -H "Authorization: Bearer $GHPAT_TOKEN" \
-        -H "X-GitHub-Api-Version: 2022-11-28" \
-        https://api.github.com/repos/AthreyaRay/testingAWSStack/statuses/$BUILDKITE_COMMIT \
-        -d '{"state": "success", "target_url": "https://buildkite.com/AthreyaRay/testingAWSStack", "description": "Group steps completed", "context": "buildkite/athreya-test1"}'
-    else
-      echo "Group steps failed, skipping GitHub status update."
-    fi
+# - label: 'Step 5: Update GitHub Status'
+#   command: |
+#     outcome=$(buildkite-agent step get "state" --step "shopify")
+#     if [ "$outcome" != "hard_failed" ]; then
+#       echo "Updating GitHub status for parent pipeline with commit hash: $PARENT_COMMIT_HASH"
+#       curl -L \
+#         -X POST \
+#         -H "Accept: application/vnd.github+json" \
+#         -H "Authorization: Bearer $GHPAT_TOKEN" \
+#         -H "X-GitHub-Api-Version: 2022-11-28" \
+#         https://api.github.com/repos/AthreyaRay/testingAWSStack/statuses/$BUILDKITE_COMMIT \
+#         -d '{"state": "success", "target_url": "https://buildkite.com/AthreyaRay/testingAWSStack", "description": "Group steps completed", "context": "buildkite/athreya-test1"}'
+#     else
+#       echo "Group steps failed, skipping GitHub status update."
+#     fi
 
 # - block: "Manual approval before sleep step"
 #   prompt: "Do you want to proceed with the sleep step?"
 
 - label: 'Step 6: Sleep for Debugging'
-  command: sleep 100 && exit 1
+  command: sleep 10 && exit 1
 
 
 
